Repository ILGOB/It-sME, pull requests merged in 2023-02, with the labels that each got.

#81 :construction: :sparkles: (feature/totalCV) 카테고리 테이블 컴포넌트 생성 #80
  ItsME.xcodeproj/project.pbxproj
  ItsME/Entities/ResumeItem.swift
  ItsME/Presentation/Common/Cells/CategoryCell.swift
  ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
  ItsME/Presentation/Scenes/TotalCV/TotalCVViewModel.swift
Labels: 검토 요청, 처리 전

#83 :zap: DB 에서 데이터를 가져오는 중 발생하는 에러를 콘솔에 출력하여 확인하기 위한 Decoder 클래스 생성
  ItsME.xcodeproj/project.pbxproj
  ItsME/Repositories/CVRepository.swift
  ItsME/Utils/DefaultJsonDecoder.swift
Labels: 처리 전

#79 :zap: 프로필 수정 화면 이동의 내부 구현 변경
  ItsME/Entities/UserInfo.swift
  ItsME/Entities/UserInfoItem.swift
  ItsME/Presentation/Scenes/EditProfile/EditProfileViewController.swift
  ItsME/Presentation/Scenes/EditProfile/EditProfileViewModel.swift
  ItsME/Presentation/Scenes/EditProfile/OtherItemEditing/OtherItemEditingViewController.swift
  ItsME/Presentation/Scenes/Home/HomeViewController.swift
  ItsME/Presentation/Scenes/Home/HomeViewModel.swift
Labels: 처리 전

#85 섹션에 대한 작업 미완
  ItsME/Presentation/Common/Cells/CategoryCell.swift
  ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
  ItsME/Presentation/Scenes/TotalCV/TotalCVViewModel.swift
  ItsME/Repositories/CVRepository.swift
Labels: 검토 요청, 처리 전

#90 섹션에 대한 작업 완료
  ItsME.xcodeproj/project.pbxproj
  ItsME/Presentation/Common/TableSection/CategoryHeaderView.swift
  ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
  ItsME/Repositories/CVRepository.swift
Labels: 검토 요청, 처리 전

#89 :construction: 프로필 수정화면 관련 기능 구현
  ItsME.xcodeproj/project.pbxproj
  ItsME/Entities/UserInfo.swift
  ItsME/Presentation/Common/Component/ProfileInfoComponent.swift
  ItsME/Presentation/Common/Component/TotalUserInfoItemStackView.swift
  ItsME/Presentation/Scenes/EditProfile/BirthdayEditing/BirthdayEditingViewController.swift
  ItsME/Presentation/Scenes/EditProfile/EditProfileViewController.swift
  ItsME/Presentation/Scenes/EditProfile/EditProfileViewModel.swift
  ItsME/Presentation/Scenes/EditProfile/OtherItem/CommonView/UserInfoItemInputView.swift
  ItsME/Presentation/Scenes/EditProfile/OtherItem/NewOtherItem/NewOtherItemViewController.swift
  ItsME/Presentation/Scenes/EditProfile/OtherItem/OtherItemEditing/OtherItemEditingViewController.swift
  ItsME/Presentation/Scenes/EditProfile/OtherItemEditing/OtherItemEditingViewController.swift
  ItsME/Utils/Extensions/Array+SafeIndex.swift
  ItsME/Utils/UIView+.swift
Labels: 처리 전

#96 :recycle: (feature/fix) 다크모드 적용가능한 색상으로 변경
  ItsME/Presentation/Common/Component/ProfileInfoComponent.swift
  ItsME/Presentation/Scenes/Home/HomeViewController.swift
Labels: 검토 요청

#99 :construction: 프로필 수정 화면의 전체적인 UI 개선
  ItsME.xcodeproj/project.pbxproj
  ItsME/Presentation/Common/Cells/CategoryCell.swift
  ItsME/Presentation/Common/Cells/EducationCell.swift
  ItsME/Presentation/Common/Component/TotalUserInfoItemStackView.swift
  ItsME/Presentation/Common/TableView/IntrinsicHeightTableView.swift
  ItsME/Presentation/Scenes/EditProfile/EditProfileViewController.swift
  ItsME/Presentation/Scenes/EditProfile/OtherItem/CommonView/Cell/ContentsInputCell.swift
  ItsME/Presentation/Scenes/EditProfile/OtherItem/CommonView/Cell/IconInputCell.swift
  ItsME/Presentation/Scenes/EditProfile/OtherItem/CommonView/TableView/UserInfoItemInputTableView.swift
  ItsME/Presentation/Scenes/EditProfile/OtherItem/CommonView/UserInfoItemInputView.swift
  ItsME/Presentation/Scenes/EditProfile/OtherItem/NewOtherItem/NewOtherItemViewController.swift
  ItsME/Presentation/Scenes/EditProfile/OtherItem/OtherItemEditing/OtherItemEditingViewController.swift
  ItsME/Utils/Protocols/Reusable.swift
Labels: 처리 중

#100 :sparkles: (feature/totalCV) #97 자기소개 테이블 컴포넌트 생성 및 적용
  ItsME.xcodeproj/project.pbxproj
  ItsME/Presentation/Common/Cells/CategoryCell.swift
  ItsME/Presentation/Common/Cells/CoverLetterCell.swift
  ItsME/Presentation/Common/Cells/EducationCell.swift
  ItsME/Presentation/Common/TableSection/CoverLetterHeaderView.swift
  ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
  ItsME/Presentation/Scenes/TotalCV/TotalCVViewModel.swift
Labels: 처리 전

#101 IconInputCell 에 ViewModel 적용
  ItsME.xcodeproj/project.pbxproj
  ItsME/Entities/UserInfoItem.swift
  ItsME/Presentation/Common/TableView/IntrinsicHeightTableView.swift
  ItsME/Presentation/Scenes/EditProfile/OtherItem/CommonView/Cell/IconInputCell.swift
  ItsME/Presentation/Scenes/EditProfile/OtherItem/CommonView/Cell/IconInputViewModel.swift
  ItsME/Presentation/Scenes/EditProfile/OtherItem/CommonView/TableView/UserInfoItemInputTableView.swift
  ItsME/Presentation/Scenes/EditProfile/OtherItem/NewOtherItem/NewOtherItemViewController.swift
  ItsME/Presentation/Scenes/EditProfile/OtherItem/OtherItemEditing/OtherItemEditingViewController.swift
Labels: 처리 전

#102 :lipstick: :zap: :fire: 프로필 수정 화면 UI 개선
  ItsME.xcodeproj/project.pbxproj
  ItsME/Presentation/Common/Component/ProfileInfoComponent.swift
  ItsME/Presentation/Common/TableView/IntrinsicHeightTableView.swift
  ItsME/Presentation/Scenes/EditProfile/CommonView/EditProfileViewController+HeaderLabel.swift
  ItsME/Presentation/Scenes/EditProfile/EditProfileViewController.swift
Labels: 처리 전

#103 :sparkles: :construction: (feature/totalCV) 수정 버튼 눌렀을 때 레이아웃 조정
  ItsME.xcodeproj/project.pbxproj
  ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
Labels: 검토 요청, 처리 전

#104 :zap: 프로필 수정 화면 구현 방법 변경
  ItsME.xcodeproj/project.pbxproj
  ItsME/Entities/UserInfo.swift
  ItsME/Presentation/Common/Component/ProfileInfoComponent.swift
  ItsME/Presentation/Scenes/EditProfile/CommonView/UserInfoItemCell.swift
  ItsME/Presentation/Scenes/EditProfile/EditProfileViewController.swift
  ItsME/Presentation/Scenes/EditProfile/EditProfileViewModel.swift
  ItsME/Presentation/Scenes/EditProfile/OtherItem/OtherItemEditing/OtherItemEditingViewController.swift
Labels: 처리 전

#113 :sparkles: :zap: :construction: (feature/totalCV) 셀 사이 간격 조정 및 setEdting을 활용한 수정 모드 적용
  ItsME/Presentation/Common/Cells/CategoryCell.swift
  ItsME/Presentation/Common/Cells/CoverLetterCell.swift
  ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
Labels: 처리 전

#119 :sparkles: :construction: (feature/totalCV) 항목 추가버튼 생성
  ItsME.xcodeproj/project.pbxproj
  ItsME/Presentation/Common/Component/EditModeAddButton.swift
  ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
Labels: 처리 전

#121 :art: :lipstick: (feature/totalCV) #118 EditModeAddButton 의존성 제거 및 버튼 조정
  ItsME.xcodeproj/project.pbxproj
  ItsME/Presentation/Common/Component/EditModeAddButton.swift
  ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
Labels: 처리 전

#123 :construction: :sparkles: (feature/totalCV) #122, TotalCVViewModel 수정
  ItsME/Entities/CoverLetter.swift
  ItsME/Entities/CoverLetterItem.swift
  ItsME/Entities/Resume.swift
  ItsME/Entities/ResumeCategory.swift
  ItsME/Entities/ResumeItem.swift
  ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
  ItsME/Presentation/Scenes/TotalCV/TotalCVViewModel.swift
Labels: 처리 전
