Repository ILGOB/It-sME, pull requests merged in 2023-01, with the labels that each got.

#52 프로필 수정 화면 작업 50% 완료
  ItsME.xcodeproj/project.pbxproj
  ItsME/Entities/EducationItem.swift
  ItsME/Entities/UserInfo.swift
  ItsME/Presentation/Common/Cells/EducationCell.swift
  ItsME/Presentation/Common/Component/ItemAddButton.swift
  ItsME/Presentation/Common/Component/TotalUserInfoItemStackView.swift
  ItsME/Presentation/Common/TableView/IntrinsicHeightTableView.swift
  ItsME/Presentation/Scenes/EditProfile/EditProfileViewController.swift
  ItsME/Presentation/Scenes/EditProfile/EditProfileViewModel.swift
  ItsME/Utils/Extensions/UIButton+.swift
Labels: 처리 전

#62 :construction: (feature/totalCV) 데이터 바인딩 작업
  ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
Labels: 도움 요청, 처리 중

#66 :construction: (feature/totalCV) #57 TotalViewModel과 HomeViewController를 subject로 연결, #65 네비게이션 타이틀 Large로 설정
  ItsME.xcodeproj/project.pbxproj
  ItsME/Presentation/Common/Component/CVCard.swift
  ItsME/Presentation/Scenes/Home/HomeViewController.swift
  ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
  ItsME/Presentation/Scenes/TotalCV/TotalCVViewModel.swift
Labels: 검토 요청, 처리 중, 질문 사항

#69 항목 추가 버튼 기능 구현
  ItsME.xcodeproj/project.pbxproj
  ItsME/Presentation/Common/Cells/EducationCell.swift
  ItsME/Presentation/Scenes/EditProfile/AddressEditing/AddressEditingViewController.swift
  ItsME/Presentation/Scenes/EditProfile/BirthdayEditing/BirthdayEditingViewController.swift
  ItsME/Presentation/Scenes/EditProfile/EditProfileViewController.swift
  ItsME/Presentation/Scenes/EditProfile/EditProfileViewModel.swift
  ItsME/Presentation/Scenes/EditProfile/EmailEditing/EmailEditingViewController.swift
  ItsME/Presentation/Scenes/EditProfile/OtherItemEditing/OtherItemEditingViewController.swift
  ItsME/Presentation/Scenes/EditProfile/PhoneNumberEditing/PhoneNumberEditingViewController.swift
  ItsME/Presentation/Scenes/Home/HomeViewController.swift
  ItsME/Utils/Extensions/Rx+Ext.swift
Labels: 처리 전

#72 :construction: (feature/totalCV) #71 프로필 사진 완성
  ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
Labels: 검토 요청, 처리 전

#74 :construction: :sparkles: (feature/totalCV) #73 유저인포 컴포넌트 기능 구현
  ItsME/Presentation/Common/Component/ProfileInfoComponent.swift
  ItsME/Presentation/Common/Component/TotalUserInfoItemStackView.swift
  ItsME/Presentation/Scenes/Home/HomeViewController.swift
  ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
Labels: 검토 요청, 처리 전

#77 :construction: :sparkles: (feature/totalCV) 학력 테이블뷰 생성 #76
  ItsME/Presentation/Scenes/TotalCV/TotalCVViewController.swift
Labels: 검토 요청, 처리 전
